### PR TITLE
Farmer's Market site

### PR DESCRIPTION
**Pull request by hieyou1**
# Changes
Adds farmer's market site

# Depends on
Outreach analytics server (not set up yet)
.env vault (contact me to get secrets)

### CODE REVIEW

**Review by navickasm — CHANGES_REQUESTED** [review]
1. Are we using Open Sans or DM Sans? Personally I like DM Sans more but we would have to use it across the board.
2. Idk about this logo modification because I couldn't figure out what it was until it was a lot bigger than it will be in print
3. The "add to calendar" and flyer buttons are a bit big, could we restructure them and make the ics button just say "Add to Calendar"

Other than that it looks ok

**Comment by hieyou1** [comment]
> 1. Are we using Open Sans or DM Sans? Personally I like DM Sans more but we would have to use it across the board.

Where is each currently being used (@navickasm)? We'll use whichever one is easier to refactor, unless one is particularly exciting

> 2. Idk about this logo modification because I couldn't figure out what it was until it was a lot bigger than it will be in print

K- I think it's important to have our branding somewhere on there, and we need the bottom-right for the QR. I can make the bottom right be the logo online, but what are our thoughts for including it in the print copy?

> 3. The "add to calendar" and flyer buttons are a bit big, could we restructure them and make the ics button just say "Add to Calendar"

fixed

(edit: fix styles)

**Review by navickasm — COMMENTED** [review]
1. Font issue
I've used Open Sans everywhere so far but I kinda like the look of DM Sans more. If we decide to fully change it (which I want to do) we can do that.

2. Logo Modification
Sorry- I was being a bit unclear. I was talking about the cowboy hat and wheat hanging out of our logo's "mouth". I'm fine with the logo being there but not modifying a logo like that is one of the cardinal rules of branding.

3. Other things
    - Are you okay with me going through and refactoring and combinding the CSS after this PR is merged?
    - Can I make a commit to change how the buttons are the way I envisioned them?

Other than that everything looks OK but I'd like to go through and change a bit of stuff and see if you're OK with it :) Lmk if I'm able to.

**Comment by hieyou1** [comment]
> I've used Open Sans everywhere so far but I kinda like the look of DM Sans more. If we decide to fully change it (which I want to do) we can do that.

Let me make sure Ethan doesn't have any extra insight, but I'm pretty much fine with whatever. I like consistency tho 👍 
> Sorry- I was being a bit unclear. I was talking about the cowboy hat and wheat hanging out of our logo's "mouth". I'm fine with the logo being there but not modifying a logo like that is one of the cardinal rules of branding.

Ah gotcha. Sounds good- I think we still want our logo on there though, at least. We might need to refactor the flyer in order to accomplish this. Open to thoughts
   
> Are you okay with me going through and refactoring and combinding the CSS after this PR is merged? 

Yeah- I straight-up ripped the CSS from the activities night, so yes after this PR let's fix our CSS in a new PR where we can talk more about establishing design language & stuff like that across the site

Edit: If you want to fix the CSS now, I'd recommend double branching (meaning, make another branch based on this branch and fix the CSS there). That way we won't have to deal with merge conflicts later on down the line.

> Can I make a commit to change how the buttons are the way I envisioned them?

Yes. Also-- [there's a feature](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request#adding-comments-to-a-pull-request) where you're able to "suggest changes" on GitHub, which is kind of like a commit-- except It's optional, and you can discuss it directly, inline, before actually committing said changes. That way you don't need to ask for permission and stuff, because you don't need to worry about rollbacks if people disagree with the change. It's kind of like a mini-PR inside of a PR. Git is big at work so lmk if you need any help with anything.

**Pull request closed without merging**
